markdown: kramdown
highlighter: rouge
relative_permalinks: false
permalink: /blog/:title/
excerpt_separator: <!--more-->
twitter: Dhruv Ambaliya
twitter_username: Dhruv Ambaliya
gauges_id:
google_analytics_id:
production_url: https://hacksofdhruv.me
repository: https://github.com/dhruv-ambaliya/dhruv-ambaliya.github.io.git
url: https://dhruv-ambaliya.github.io
plugins:
  - jekyll-sitemap

collections:
  docs:
    output: true
imagemagick_convert: /usr/local/bin/convert
imagemagick_identify: /usr/local/bin/identify
