name: HacksofDhruv.me
description: Security Research and Penetration Testing Blog
  
markdown: kramdown
highlighter: rouge
relative_permalinks: false
permalink: /blog/:title/
excerpt_separator: <!--more-->
twitter:
  username: Dhruv_Ambaliya_
  card: summary
github: Dhruv Ambaliya
github_username: dhruv-ambaliya
linkedin: dhruv-ambaliya-
linkedin_username: dhruv-ambaliya-
social:
  name: Dhruv Ambaliya
  links:
    - https://x.com/Dhruv_Ambaliya_
    - https://www.linkedin.com/in/dhruv-ambaliya-
    - https://github.com/dhruv-ambaliya

logo: "/img/hacksofdhruv.png"
gauges_id:
google_analytics_id: G-KGN0NHY04Y
google_site_verification: _EUyQqszRKbJZ2aen5wfzpzrMS4jyzuLAjBWucm4oWg
production_url: https://hacksofdhruv.me
repository: https://github.com/dhruv-ambaliya/dhruv-ambaliya.github.io
url: https://hacksofdhruv.me
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

collections:
  docs:
    output: true
imagemagick_convert: /usr/local/bin/convert
imagemagick_identify: /usr/local/bin/identify
